contingenciesSection=Contingencies
generator=generator
hvdcLine=HVDC
invalidContingency=Contingency %s has not been created because equipment %s
invalidContingencyNetwork=does not exist in the network
invalidContingencyNetworkType=is of %s type in contingency and of %s type in the network
invalidContingencyType=is of %s type
invalidMetrixDslDataContingency=The %s will not be able to operate in curative on contingency %s because it is not defined in contingencies script
invalidMetrixRemedialConstraint=because equipment %s is not monitored on contingency
invalidMetrixRemedialContingency=because contingency %s is not defined in contingencies script
invalidRemedial=The remedial at line %s will not be taken into account
invalidRemedialActionType=because equipment %s is not a Branch or Switch type
invalidRemedialConstraintType=because equipment %s is not a Branch type
invalidRemedialFile=Remedial file will not be recognized because line %d
invalidRemedialFileAction=is malformed (number of actions)
invalidRemedialFileComment=contains a comment
invalidRemedialFileEmptyElement=contains an empty element
invalidRemedialFileEndLine=does not end with semicolon
invalidRemedialFileHeader=is malformed (header)
invalidRemedialFileLine=is malformed
invalidRemedialFileNbRemedialMoreLines=because remedial number in header (NB = %d) is greater than the line number of the remedial (%d)
invalidRemedialNbRemedialLessLines=because the line number of the remedial is greater than the remedial number in header (NB = %d)
invalidRemedialNetwork=because equipment %s does not exist in the network
load=load
phaseTapChanger=PST
remedialsSection=Remedials
